import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { Breadcrumbs } from "../../components/shared/Breadcrumbs";
import { usePlatform } from "../../app/providers/PlatformProvider";
import { EmptyState, StatusPill } from "../../components/shared/Widgets";
import { formatDateTime } from "../../lib/dates";
import { formatMoney, paymentMethodLabel } from "../../lib/money";
import { registrationBundle } from "../../repositories/platform";
import { fetchPayment, type RemotePayment } from "../../services/payments";

export function ReceiptPage() {
  const { registrationId = "" } = useParams();
  const { db, live } = usePlatform();
  const [params] = useSearchParams();
  const bundle = registrationBundle(db, registrationId);
  const paymentParam = params.get("payment");
  if (live && paymentParam && (!bundle?.payment || bundle.payment.status !== "paid")) return <RemoteReceipt paymentId={paymentParam} />;
  if (!bundle?.payment) {
    return <div className="nt-container" style={{ padding: 48 }}><EmptyState title="Receipt not found" body="Complete checkout to generate a receipt." /></div>;
  }
  const { attendee, event, ticket, payment, registration } = bundle;

  return (
    <div className="nt-container nt-page nt-form-page nt-receipt-page" style={{ maxWidth: 820 }}>
      <Breadcrumbs items={[{ label: "Events", to: "/events" }, { label: event.title, to: `/events/${event.slug}` }, { label: "Receipt" }]} />
      <div className="nt-receipt-toolbar no-print">
        <div>
          <p className="nt-kicker">Payment record</p>
          <h1>Receipt</h1>
        </div>
        <button type="button" className="nt-btn" onClick={() => window.print()}>Print / download</button>
      </div>

      <article className="nt-card nt-receipt-card">
        <header className="nt-receipt-header">
          <div className="nt-footer-brand nt-receipt-brand">
            <span className="nt-mark" />
            <div>
              <strong>Neurotech Events</strong>
              <span>by Neurotech Africa</span>
            </div>
          </div>
          <div className="nt-receipt-number">
            <span>Receipt reference</span>
            <strong>{registration.ticketNumber}</strong>
            <small>{formatDateTime(payment.updatedAt)}</small>
          </div>
        </header>

        <div className="nt-receipt-callout">
          <div>
            <span>Payment status</span>
            <StatusPill value={payment.status} />
          </div>
          <div>
            <span>Amount paid</span>
            <strong>{formatMoney(payment.amount)}</strong>
          </div>
        </div>

        <div className="nt-receipt-parties">
          <section>
            <p className="nt-kicker">Billed to</p>
            <strong>{attendee.fullName}</strong>
            <span>{attendee.organization}</span>
            <span>{attendee.email}</span>
            <span>{attendee.phone}</span>
          </section>
          <section>
            <p className="nt-kicker">Payment</p>
            <strong>{paymentMethodLabel(payment.method)}</strong>
            <span>Reference {payment.reference}</span>
            <span>{event.title}</span>
          </section>
        </div>

        <div className="nt-receipt-lines">
          <div><span>{ticket.name} · {event.title}</span><strong>{formatMoney(ticket.price)}</strong></div>
          <div><span>VAT {db.settings.vatPercent}%</span><strong>{formatMoney(payment.amount - ticket.price)}</strong></div>
          <div className="nt-receipt-total"><span>Total</span><strong>{formatMoney(payment.amount)}</strong></div>
        </div>

        <footer className="nt-receipt-note">{live ? "Payment processed by Snippe and confirmed by the Neurotech Events server · not a fiscal receipt." : "Demo invoice · not a fiscal receipt · generated by the Neurotech Events frontend prototype."}</footer>
      </article>
    </div>
  );
}

/** Receipt for a live payment, read straight from the server (works for guest checkouts too). */
function RemoteReceipt({ paymentId }: { paymentId: string }) {
  const [payment, setPayment] = useState<RemotePayment | null>(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    fetchPayment(paymentId).then(setPayment).catch(() => setFailed(true));
  }, [paymentId]);
  if (failed) return <div className="nt-container" style={{ padding: 48 }}><EmptyState title="Receipt not found" body="This payment could not be found." /></div>;
  if (!payment) return <div className="nt-container" style={{ padding: 48 }}><p className="nt-muted" role="status">Loading receipt…</p></div>;
  return (
    <div className="nt-container nt-page nt-form-page nt-receipt-page" style={{ maxWidth: 820 }}>
      <Breadcrumbs items={[{ label: "Events", to: "/events" }, { label: payment.event_title, to: `/events/${payment.event_slug}` }, { label: "Receipt" }]} />
      <div className="nt-receipt-toolbar no-print">
        <div><p className="nt-kicker">Payment record</p><h1>Receipt</h1></div>
        <button type="button" className="nt-btn" onClick={() => window.print()}>Print / download</button>
      </div>
      <article className="nt-card nt-receipt-card">
        <header className="nt-receipt-header">
          <div className="nt-footer-brand nt-receipt-brand"><span className="nt-mark" /><div><strong>Neurotech Events</strong><span>by Neurotech Africa</span></div></div>
          <div className="nt-receipt-number"><span>Ticket</span><strong>{payment.ticket_number}</strong><small>{formatDateTime(payment.paid_at ?? payment.updated_at)}</small></div>
        </header>
        <div className="nt-receipt-callout">
          <div><span>Payment status</span><StatusPill value={payment.status} /></div>
          <div><span>Amount</span><strong>{formatMoney(payment.amount, payment.currency)}</strong></div>
        </div>
        <div className="nt-receipt-parties">
          <section><p className="nt-kicker">Billed to</p><strong>{payment.attendee_name}</strong><span>{payment.attendee_email}</span></section>
          <section><p className="nt-kicker">Payment</p><strong>{paymentMethodLabel(payment.method)}</strong><span>Reference {payment.reference}</span><span>{payment.event_title}</span></section>
        </div>
        <div className="nt-receipt-lines">
          <div><span>{payment.ticket_name} · {payment.event_title}</span><strong>{formatMoney(payment.amount, payment.currency)}</strong></div>
          <div className="nt-receipt-total"><span>Total (VAT included)</span><strong>{formatMoney(payment.amount, payment.currency)}</strong></div>
        </div>
        <footer className="nt-receipt-note">Payment processed by Snippe and confirmed by the Neurotech Events server · not a fiscal receipt.</footer>
      </article>
    </div>
  );
}
