import { useParams } from "react-router-dom";
import { usePlatform } from "../../app/providers/PlatformProvider";
import { EmptyState, StatusPill } from "../../components/shared/Widgets";
import { formatDateTime } from "../../lib/dates";
import { formatMoney, paymentMethodLabel } from "../../lib/money";
import { registrationBundle } from "../../repositories/platform";

export function ReceiptPage() {
  const { registrationId = "" } = useParams();
  const { db } = usePlatform();
  const bundle = registrationBundle(db, registrationId);
  if (!bundle?.payment) {
    return <div className="nt-container" style={{ padding: 48 }}><EmptyState title="Receipt not found" body="Complete checkout to generate a receipt." /></div>;
  }
  const { attendee, event, ticket, payment, registration } = bundle;

  return (
    <div className="nt-container nt-page nt-form-page nt-receipt-page" style={{ maxWidth: 820 }}>
      <div className="nt-receipt-toolbar no-print">
        <div>
          <p className="nt-kicker">Payment record</p>
          <h1>Receipt</h1>
        </div>
        <button type="button" className="nt-btn" onClick={() => window.print()}>Print / download</button>
      </div>

      <article className="nt-card nt-receipt-card">
        <header className="nt-receipt-header">
          <div className="nt-footer-brand nt-receipt-brand">
            <span className="nt-mark" />
            <div>
              <strong>Neurotech Events</strong>
              <span>by Neurotech Africa</span>
            </div>
          </div>
          <div className="nt-receipt-number">
            <span>Receipt reference</span>
            <strong>{registration.ticketNumber}</strong>
            <small>{formatDateTime(payment.updatedAt)}</small>
          </div>
        </header>

        <div className="nt-receipt-callout">
          <div>
            <span>Payment status</span>
            <StatusPill value={payment.status} />
          </div>
          <div>
            <span>Amount paid</span>
            <strong>{formatMoney(payment.amount)}</strong>
          </div>
        </div>

        <div className="nt-receipt-parties">
          <section>
            <p className="nt-kicker">Billed to</p>
            <strong>{attendee.fullName}</strong>
            <span>{attendee.organization}</span>
            <span>{attendee.email}</span>
            <span>{attendee.phone}</span>
          </section>
          <section>
            <p className="nt-kicker">Payment</p>
            <strong>{paymentMethodLabel(payment.method)}</strong>
            <span>Reference {payment.reference}</span>
            <span>{event.title}</span>
          </section>
        </div>

        <div className="nt-receipt-lines">
          <div><span>{ticket.name} · {event.title}</span><strong>{formatMoney(ticket.price)}</strong></div>
          <div><span>VAT {db.settings.vatPercent}%</span><strong>{formatMoney(payment.amount - ticket.price)}</strong></div>
          <div className="nt-receipt-total"><span>Total</span><strong>{formatMoney(payment.amount)}</strong></div>
        </div>

        <footer className="nt-receipt-note">Demo invoice · not a fiscal receipt · generated by the Neurotech Events frontend prototype.</footer>
      </article>
    </div>
  );
}
