"""create core platform tables

Revision ID: 0e5f3e6a33fc
Revises:
Create Date: 2026-09-22 19:00:28.276509
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0e5f3e6a33fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("brand_name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("default_city", sa.String(length=120), nullable=True),
        sa.Column("default_country", sa.String(length=120), nullable=True),
        sa.Column("vat_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("registration_open_by_default", sa.Boolean(), nullable=False),
        sa.Column("notify_on_registration", sa.Boolean(), nullable=False),
        sa.Column("notify_on_payment", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "speakers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("initials", sa.String(length=8), nullable=True),
        sa.Column("role", sa.String(length=200), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("track", sa.String(length=120), nullable=True),
        sa.Column("social_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speakers")),
    )
    op.create_table(
        "sponsors",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "title",
                "platinum",
                "gold",
                "silver",
                "partner",
                name="sponsor_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("contact", sa.String(length=320), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsors")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "attendee",
                "event_staff",
                "event_admin",
                "platform_admin",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "venues",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venues")),
    )
    op.create_table(
        "attendees",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("role_title", sa.String(length=200), nullable=True),
        sa.Column("dietary", sa.Text(), nullable=True),
        sa.Column("accessibility", sa.Text(), nullable=True),
        sa.Column(
            "interests", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("is_demo_user", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attendees_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendees")),
        sa.UniqueConstraint("user_id", name=op.f("uq_attendees_user_id")),
    )
    op.create_index(op.f("ix_attendees_email"), "attendees", ["email"], unique=False)
    op.create_table(
        "events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=True),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("subtitle", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("theme", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "ongoing",
                "completed",
                "cancelled",
                name="event_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum("physical", "online", "hybrid", name="event_format", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("banner_label", sa.String(length=120), nullable=True),
        sa.Column(
            "highlights", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "faqs", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("capacity >= 0", name=op.f("ck_events_capacity_non_negative")),
        sa.CheckConstraint("ends_at >= starts_at", name=op.f("ck_events_ends_after_starts")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venues.id"], name=op.f("fk_events_venue_id_venues"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("slug", name=op.f("uq_events_slug")),
    )
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index(op.f("ix_events_venue_id"), "events", ["venue_id"], unique=False)
    op.create_table(
        "certificates",
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("certificate_code", sa.String(length=40), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_certificates_attendee_id_attendees"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_certificates_event_id_events"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("attendee_id", "event_id", name="uq_certificates_attendee_event"),
        sa.UniqueConstraint("certificate_code", name=op.f("uq_certificates_certificate_code")),
    )
    op.create_index(op.f("ix_certificates_attendee_id"), "certificates", ["attendee_id"], unique=False)
    op.create_index(op.f("ix_certificates_event_id"), "certificates", ["event_id"], unique=False)
    op.create_table(
        "communications",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum("email", "sms", "push", name="communication_channel", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "audience",
            sa.Enum(
                "all",
                "paid",
                "student",
                "vip",
                "checked-in",
                name="audience_segment",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "sent", name="communication_status", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_communications_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_communications_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communications")),
    )
    op.create_index(op.f("ix_communications_event_id"), "communications", ["event_id"], unique=False)
    op.create_index(op.f("ix_communications_status"), "communications", ["status"], unique=False)
    op.create_table(
        "connections",
        sa.Column("from_attendee_id", sa.Uuid(), nullable=False),
        sa.Column("to_attendee_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("from_attendee_id <> to_attendee_id", name=op.f("ck_connections_not_self")),
        sa.ForeignKeyConstraint(
            ["from_attendee_id"],
            ["attendees.id"],
            name=op.f("fk_connections_from_attendee_id_attendees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_attendee_id"],
            ["attendees.id"],
            name=op.f("fk_connections_to_attendee_id_attendees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
        sa.UniqueConstraint("from_attendee_id", "to_attendee_id", name="uq_connections_pair"),
    )
    op.create_index(op.f("ix_connections_from_attendee_id"), "connections", ["from_attendee_id"], unique=False)
    op.create_index(op.f("ix_connections_to_attendee_id"), "connections", ["to_attendee_id"], unique=False)
    op.create_table(
        "networking_profiles",
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("public_name", sa.String(length=200), nullable=False),
        sa.Column("initials", sa.String(length=8), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column(
            "interests", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"],
            ["attendees.id"],
            name=op.f("fk_networking_profiles_attendee_id_attendees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_networking_profiles")),
        sa.UniqueConstraint("attendee_id", name=op.f("uq_networking_profiles_attendee_id")),
    )
    op.create_table(
        "notifications",
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "registration",
                "schedule",
                "reminder",
                "announcement",
                "payment",
                "certificate",
                name="notification_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_notifications_attendee_id_attendees"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_attendee_id"), "notifications", ["attendee_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("speaker_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column("day_label", sa.String(length=60), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("speaker_label", sa.String(length=200), nullable=True),
        sa.Column("room", sa.String(length=120), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "ceremony",
                "keynote",
                "panel",
                "workshop",
                "session",
                "showcase",
                "roundtable",
                "pitch",
                "demo",
                "break",
                "networking",
                name="session_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_sessions_event_id_events"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"], ["speakers.id"], name=op.f("fk_sessions_speaker_id_speakers"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_event_id"), "sessions", ["event_id"], unique=False)
    op.create_index(op.f("ix_sessions_speaker_id"), "sessions", ["speaker_id"], unique=False)
    op.create_table(
        "sponsor_events",
        sa.Column("sponsor_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_sponsor_events_event_id_events"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"], ["sponsors.id"], name=op.f("fk_sponsor_events_sponsor_id_sponsors"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sponsor_id", "event_id", name=op.f("pk_sponsor_events")),
    )
    op.create_table(
        "ticket_types",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.String(length=40), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("perks", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("sales_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("capacity >= 0", name=op.f("ck_ticket_types_capacity_non_negative")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_ticket_types_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_ticket_types_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_types")),
    )
    op.create_index(op.f("ix_ticket_types_event_id"), "ticket_types", ["event_id"], unique=False)
    op.create_table(
        "timeline_milestones",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("done", "live", "scheduled", name="milestone_status", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("day_index", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_timeline_milestones_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_milestones")),
    )
    op.create_index(op.f("ix_timeline_milestones_event_id"), "timeline_milestones", ["event_id"], unique=False)
    op.create_table(
        "registrations",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "cancelled",
                name="registration_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("ticket_number", sa.String(length=40), nullable=False),
        sa.Column("dietary", sa.Text(), nullable=True),
        sa.Column("accessibility", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_registrations_attendee_id_attendees"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_registrations_event_id_events"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_type_id"],
            ["ticket_types.id"],
            name=op.f("fk_registrations_ticket_type_id_ticket_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint("ticket_number", name=op.f("uq_registrations_ticket_number")),
    )
    op.create_index(op.f("ix_registrations_attendee_id"), "registrations", ["attendee_id"], unique=False)
    op.create_index("ix_registrations_event_attendee", "registrations", ["event_id", "attendee_id"], unique=False)
    op.create_index(op.f("ix_registrations_event_id"), "registrations", ["event_id"], unique=False)
    op.create_index(op.f("ix_registrations_status"), "registrations", ["status"], unique=False)
    op.create_index(op.f("ix_registrations_ticket_type_id"), "registrations", ["ticket_type_id"], unique=False)
    op.create_table(
        "saved_sessions",
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_saved_sessions_attendee_id_attendees"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_saved_sessions_session_id_sessions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attendee_id", "session_id", name=op.f("pk_saved_sessions")),
    )
    op.create_table(
        "check_ins",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_number", sa.String(length=40), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("checked_in_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_check_ins_attendee_id_attendees"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["checked_in_by_user_id"],
            ["users.id"],
            name=op.f("fk_check_ins_checked_in_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_check_ins_event_id_events"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_check_ins_registration_id_registrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_ins")),
    )
    op.create_index(op.f("ix_check_ins_event_id"), "check_ins", ["event_id"], unique=False)
    op.create_index(op.f("ix_check_ins_registration_id"), "check_ins", ["registration_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("attendee_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "mpesa",
                "airtel",
                "mixx",
                "halopesa",
                "card",
                "bank",
                name="payment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "paid",
                "failed",
                "cancelled",
                "refunded",
                name="payment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("provider_reference", sa.String(length=120), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payments_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["attendee_id"], ["attendees.id"], name=op.f("fk_payments_attendee_id_attendees"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_payments_event_id_events"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_payments_registration_id_registrations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("reference", name=op.f("uq_payments_reference")),
    )
    op.create_index(op.f("ix_payments_event_id"), "payments", ["event_id"], unique=False)
    op.create_index(op.f("ix_payments_registration_id"), "payments", ["registration_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "payment_events",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "pending",
                "processing",
                "paid",
                "failed",
                "cancelled",
                "refunded",
                name="payment_event_from_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "pending",
                "processing",
                "paid",
                "failed",
                "cancelled",
                "refunded",
                name="payment_event_to_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_payment_events_payment_id_payments"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
    )
    op.create_index(op.f("ix_payment_events_payment_id"), "payment_events", ["payment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_events_payment_id"), table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_registration_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_event_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_check_ins_registration_id"), table_name="check_ins")
    op.drop_index(op.f("ix_check_ins_event_id"), table_name="check_ins")
    op.drop_table("check_ins")
    op.drop_table("saved_sessions")
    op.drop_index(op.f("ix_registrations_ticket_type_id"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_status"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_event_id"), table_name="registrations")
    op.drop_index("ix_registrations_event_attendee", table_name="registrations")
    op.drop_index(op.f("ix_registrations_attendee_id"), table_name="registrations")
    op.drop_table("registrations")
    op.drop_index(op.f("ix_timeline_milestones_event_id"), table_name="timeline_milestones")
    op.drop_table("timeline_milestones")
    op.drop_index(op.f("ix_ticket_types_event_id"), table_name="ticket_types")
    op.drop_table("ticket_types")
    op.drop_table("sponsor_events")
    op.drop_index(op.f("ix_sessions_speaker_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_event_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_notifications_attendee_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("networking_profiles")
    op.drop_index(op.f("ix_connections_to_attendee_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_from_attendee_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_communications_status"), table_name="communications")
    op.drop_index(op.f("ix_communications_event_id"), table_name="communications")
    op.drop_table("communications")
    op.drop_index(op.f("ix_certificates_event_id"), table_name="certificates")
    op.drop_index(op.f("ix_certificates_attendee_id"), table_name="certificates")
    op.drop_table("certificates")
    op.drop_index(op.f("ix_events_venue_id"), table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_attendees_email"), table_name="attendees")
    op.drop_table("attendees")
    op.drop_table("venues")
    op.drop_table("users")
    op.drop_table("sponsors")
    op.drop_table("speakers")
    op.drop_table("organizations")
    # ### end Alembic commands ###
