"""add ticket codes and provider webhook events

Revision ID: 417bd1961608
Revises: 0e5f3e6a33fc
Create Date: 2026-09-22 19:40:38.928545
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "417bd1961608"
down_revision: str | Sequence[str] | None = "0e5f3e6a33fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_webhook_events",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_provider_webhook_events_payment_id_payments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_webhook_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_provider_webhook_events_provider_event"),
    )
    op.create_index(
        op.f("ix_provider_webhook_events_payment_id"), "provider_webhook_events", ["payment_id"], unique=False
    )
    if op.get_bind().dialect.name == "sqlite":
        # SQLite cannot ALTER a table to add a unique constraint. Batch mode keeps the
        # development SQLite database migration-compatible.
        with op.batch_alter_table("ticket_types", recreate="always") as batch_op:
            batch_op.add_column(sa.Column("code", sa.String(length=60), nullable=True))
            batch_op.create_unique_constraint("uq_ticket_types_event_code", ["event_id", "code"])
    else:
        op.add_column("ticket_types", sa.Column("code", sa.String(length=60), nullable=True))
        op.create_unique_constraint("uq_ticket_types_event_code", "ticket_types", ["event_id", "code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("ticket_types", recreate="always") as batch_op:
            batch_op.drop_constraint("uq_ticket_types_event_code", type_="unique")
            batch_op.drop_column("code")
    else:
        op.drop_constraint("uq_ticket_types_event_code", "ticket_types", type_="unique")
        op.drop_column("ticket_types", "code")
    op.drop_index(op.f("ix_provider_webhook_events_payment_id"), table_name="provider_webhook_events")
    op.drop_table("provider_webhook_events")
    # ### end Alembic commands ###
